# Generated by Django 6.0.4 on 2026-06-21 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_amount', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('CHARGE', 'CHARGE'), ('USE', 'USE'), ('REFUND', 'REFUND'), ('CANCEL', 'CANCEL')], max_length=10)),
                ('feature_name', models.CharField(max_length=20)),
                ('change_amount', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_transaction',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')], max_length=10)),
                ('payment_key', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='credits.plan')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
