# Generated by Django 6.0.4 on 2026-06-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_convert_genre_to_korean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='genre',
            field=models.CharField(choices=[('로맨스', '로맨스'), ('판타지', '판타지'), ('로맨스 판타지', '로맨스 판타지'), ('시대극', '시대극'), ('현대물', '현대물'), ('무협', '무협'), ('SF', 'SF'), ('공포', '공포'), ('미스터리', '미스터리'), ('기타', '기타')], max_length=10),
        ),
    ]
