"""서비스 요구사항 기준 입력/저장 제한값.

DB 컬럼 길이와 OpenAI 호출 전 방어용 API 입력 제한을 한곳에서 관리한다.
"""
from __future__ import annotations

# 요청 본문 전체 크기 제한. 큰 JSON이 OpenAI 호출까지 가는 것을 막기 위한 1차 방어.
MAX_REQUEST_BODY_BYTES = 512 * 1024  # 512KB

# 작품/회차
MAX_WORK_TITLE = 50
MAX_EPISODE_TITLE = 30
MAX_GENRE = 10
MAX_SYNOPSIS = 10000

# 번역/검수
MAX_SOURCE_TEXT = 8000
MAX_CURRENT_TRANSLATION = 24000  # 번역본은 원문보다 길어 원문 한계와 분리
MAX_CHAT_QUESTION = 1000

# 표지 생성
MAX_COVER_PROMPT = 500

# 캐릭터/관계도
MAX_CHARACTER_COUNT = 20
MAX_RELATION_CHARACTER_COUNT = 20
MAX_CHARACTER_NAME = 30
MAX_CHARACTER_AGE = 10
MAX_CHARACTER_ROLE = 5
MAX_CHARACTER_PROFILE_LABEL = 80
MAX_CHARACTER_GENDER = 5
MAX_CHARACTER_RELATIONSHIPS = 500
MAX_CHARACTER_APPEARANCE = 300
MAX_CHARACTER_DETAIL = 1000

# 저장 개수 제한
MAX_TRANSLATION_VERSIONS = 3       # 회차 × 국가별 최근 3개
MAX_COVERS_PER_WORK = 5            # 작품당 표지 5장
MAX_RELATION_MAPS_PER_WORK = 3     # 작품당 관계도 3개
MAX_GUIDES_PER_WORK = 5            # 작품당 현지화 가이드 5개

# --- 공개 테스트용 IP Rate Limit ---
# 단일 EC2/단일 컨테이너 기준 인메모리 제한값.
# 학원 네트워크에서 여러 사용자가 같은 공인 IP로 보일 수 있으므로 일반 API는 넉넉하게,
# 실제 이미지 생성(cover dryRun=false)만 비용 방어를 위해 더 강하게 제한한다.
RATE_LIMIT_DEFAULT_IP_PER_MINUTE = 60
RATE_LIMIT_DEFAULT_IP_PER_HOUR = 600

RATE_LIMIT_TRANSLATION_IP_PER_MINUTE = 20
RATE_LIMIT_TRANSLATION_IP_PER_HOUR = 300
RATE_LIMIT_TRANSLATION_GLOBAL_PER_HOUR = 1000

RATE_LIMIT_INSPECT_CHAT_IP_PER_MINUTE = 30
RATE_LIMIT_INSPECT_CHAT_IP_PER_HOUR = 500
RATE_LIMIT_INSPECT_CHAT_GLOBAL_PER_HOUR = 1500

RATE_LIMIT_CHARACTER_EXTRACT_IP_PER_MINUTE = 10
RATE_LIMIT_CHARACTER_EXTRACT_IP_PER_HOUR = 100
RATE_LIMIT_CHARACTER_EXTRACT_GLOBAL_PER_HOUR = 300

RATE_LIMIT_RELATIONSHIP_MAP_IP_PER_MINUTE = 10
RATE_LIMIT_RELATIONSHIP_MAP_IP_PER_HOUR = 100
RATE_LIMIT_RELATIONSHIP_MAP_GLOBAL_PER_HOUR = 300

RATE_LIMIT_GUIDE_IP_PER_MINUTE = 10
RATE_LIMIT_GUIDE_IP_PER_HOUR = 100
RATE_LIMIT_GUIDE_GLOBAL_PER_HOUR = 300

RATE_LIMIT_COVER_DRY_RUN_IP_PER_MINUTE = 10
RATE_LIMIT_COVER_DRY_RUN_IP_PER_HOUR = 100
RATE_LIMIT_COVER_DRY_RUN_GLOBAL_PER_HOUR = 300

RATE_LIMIT_COVER_GENERATE_IP_PER_MINUTE = 5
RATE_LIMIT_COVER_GENERATE_IP_PER_HOUR = 40
RATE_LIMIT_COVER_GENERATE_GLOBAL_PER_HOUR = 100

